version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
