spring:
  config:
    import:
      - "optional:file:.env[.properties]"
  application:
    name: video-metadata-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:myhost}:${DB_PORT:5430}/${DB_NAME:video_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: 60s
      lettuce:
        pool:
          max-active: ${REDIS_LETTUCE_MAX_ACTIVE:10}
          max-idle: ${REDIS_LETTUCE_MAX_IDLE:5}
          min-idle: ${REDIS_LETTUCE_MIN_IDLE:1}
          max-wait: ${REDIS_LETTUCE_MAX_WAIT:30s}

  webflux:
    base-path: /api

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://auth-server/.well-known/jwks.json}

  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 100
      thread-name-prefix: async-

server:
  port: 8080

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException
    instances:
      videoImportRetry:
        base-config: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 500ms
    instances:
      videoApiRateLimiter:
        base-config: default

  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 100
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
    instances:
      externalApiCircuitBreaker:
        base-config: default

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    display-request-duration: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.github.dimitryivaniuta.videometadata: DEBUG
    io.github.resilience4j: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
